name: create release

on:

  push:
    branches:
      - develop

    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      # https://semver.org/ proper release tags, more or less
      - "v[0-9]+.[0-9]+.[0-9]+"
      # prerelease tags, more or less
      - "v[0-9]+.[0-9]+.[0-9]+-*"

env:
  GIT_CHGLOG_VERSION: 0.11.2
  NODE_VERSION: 14.15.5

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build changelog
        id: git-chglog
        shell: bash
        run: |
          curl -o git-chglog_${{ env.GIT_CHGLOG_VERSION }}_linux_amd64.tar.gz -L https://github.com/git-chglog/git-chglog/releases/download/v${{ env.GIT_CHGLOG_VERSION }}/git-chglog_${{ env.GIT_CHGLOG_VERSION }}_linux_amd64.tar.gz
          tar xvzf git-chglog_${{ env.GIT_CHGLOG_VERSION }}_linux_amd64.tar.gz git-chglog
          chmod +x ./git-chglog
      - name: Generate changelog
        run: git-chglog -c .chglog/config.yml -o RELEASE_CHANGELOG.md $(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body_path: RELEASE_CHANGELOG.md