name: create release

on:

  push:
    branches:
      - develop

    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      # https://semver.org/ proper release tags, more or less
      - "v[0-9]+.[0-9]+.[0-9]+"
      # prerelease tags, more or less
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  release:
    runs-on: ubuntu-20.04
    container:
      image: golang:1.15
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: fetch tags
        run: |
          git fetch --tags

      - name: show version
        id: version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: install
        run: |
          go get github.com/git-chglog/git-chglog/cmd/git-chglog

      - name: generate changelog
        run: |
          # https://github.com/git-chglog/git-chglog#git-chglog
          $(go env GOPATH)/bin/git-chglog \
            -c .chglog/config.yml \
            -o $GITHUB_WORKSPACE/RELEASE_CHANGELOG.md \
            ${{ steps.version.outputs.VERSION }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body_path: $GITHUB_WORKSPACE/RELEASE_CHANGELOG.md